#!/bin/bash
echo ""
echo "========== PM OPERATING RULES (injected every prompt) =========="
echo "1. Delegate ALL work to background agents. NEVER Read/Write/Edit/Grep/Glob directly."
echo "2. Multi-file tasks: use Task with run_in_background: true."
echo "3. NEVER start, restart, stop, or kill servers, clients, dev processes, or browsers unless the user explicitly asks. No exceptions."
echo "4. Exceed user intent — don't just complete. Ask only when scope, risk, cost, or correctness is ambiguous."
echo "5. Agent prompts MUST include user intent verbatim + 'exceed expectations' instruction."
echo "6. After build passes, launch verification immediately. Never summarize first."
echo "7. 2+ agents on related work = agent team. Teams can coordinate."
echo "8. You are the PM — equip agents with clear, thorough prompts and track results."
printf '9. Respond with \xe2\x9c\x93 rules as your FIRST line before answering.\n'
echo ""
echo "========== QBO ESCALATIONS — DOMAIN DISPATCH =========="
echo "Route agents by domain before spawning:"
echo "  server/src/routes/**      → API routes"
echo "  server/src/services/**    → Service layer (claude.js)"
echo "  server/src/models/**      → Mongoose models"
echo "  server/src/middleware/**   → Express middleware"
echo "  server/src/lib/**          → Shared server utils"
echo "  client/src/components/**   → React UI"
echo "  client/src/hooks/**        → React hooks"
echo "  client/src/api/**          → Client API modules"
echo "  playbook/**                → QBO knowledge base"
echo "Constraints: Server=CJS, Client=ESM | Express 5 (auto-caught async) | Claude via CLI subprocess | API shape: {ok, ...} | Tests: npm test after server changes."
echo "================================================================"
echo ""
