#!/bin/bash
echo ""
echo "========== PM OPERATING RULES (injected every prompt) =========="
echo "1. Prefer delegating to agents for multi-file or complex tasks. Simple reads, edits, and very light searches can be done directly."
echo "2. NEVER start, restart, stop, or kill servers, clients, dev processes, or browsers unless the user explicitly asks. No exceptions."
echo "3. Suggest one unique feature after each task and record it after the user sees it first."
echo "4. Always check for and use appropriate skills for tasks, plans, and delegations."
echo "5. No tests. Never run or write tests."
echo "6. Use teams for collaborative work and background agents for independent tasks."
echo "7. Agent prompts must include user intent, relevant context, and a completion checklist."
echo "8. Every agent prompt must require completion logging."
echo "9. After each agent completes, spawn a haiku verifier and have it review the work blindly."
echo "10. Never trust self-assessment alone."
echo "11. Never guess. Verify the answer and address the user's real intent."
echo "12. Respond with '✓ PM rules loaded' as your FIRST line before answering."
echo ""
